
---
- name: Install PHP and Apache for PSM
  hosts: php_servers
  vars:
    install_dir: /usr/local/greatfire/psm
    psm_repo_url: https://github.com/stevenmcdonald/psm
  become: no
  remote_user: root

  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        pkg:
          - apache2
          - libapache2-mod-php
          - git
          - php
          - php-curl
          - php-mongodb
          - php-mbstring
          - php-xml
          - sudo
          - vim-nox

    # configure Apache
    - name: Disable prefork module
      ansible.builtin.file:
        path: /etc/apache2/mods-enabled/mpm_prefork.conf
        state: absent

    - name: Update apache2 worker conf
      ansible.builtin.copy:
        src: mpm_worker.conf
        dest: /etc/apache2/mods-available/mpm_worker.conf

    - name: Enable the worker module
      ansible.builtin.file:
        src: /etc/apache2/mods-available/mpm_worker.conf
        path: /etc/apache2/mods-enabled/mpm_worker.conf
        state: link

    - name: Disable the default site
      ansible.builtin.file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    - name: Install the PSM Apache config
      ansible.builtin.copy:
        src: psm_apache.conf
        dest: /etc/apache2/sites-available/psm.conf

    - name: Enable the PSM Apache config
      ansible.builtin.file:
        src: /etc/apache2/sites-available/psm.conf
        dest: /etc/apache2/sites-enabled/psm.conf
        state: link

    # configure user, directory
    - name: Create psm user
      ansible.builtin.user:
        name: psm

    - name: Create install directory
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        owner: psm
        group: psm

    - name: Pull the code
      ansible.builtin.git:
        repo: "{{ psm_repo_url }}"
        dest: "{{ install_dir }}"
        version: main
        force: yes
      become: yes
      become_user: psm

    - name: Install local.inc
      ansible.builtin.template:
        src: local.inc.j2
        dest: "{{ install_dir }}/inc/local.inc"
      become: yes
      become_user: psm

    - name: Copy Composer installer
      ansible.builtin.copy:
        src: composer-setup.php
        dest: /root/composer-setup.php

    - name: Install Composer
      ansible.builtin.shell:
        cmd: php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        chdir: /root

    - name: Install PHP depenecies
      community.general.composer:
        command: install
        working_dir: "{{ install_dir }}/inc"
      become: yes
      become_user: psm

    - name: Install mongo-full cron script
      ansible.builtin.template:
        src: mongo-full.sh.j2
        dest: "{{ install_dir }}/scripts/mongo-full.sh"
        mode: '0755'
      become: yes
      become_user: psm

    - name: Create mongo script log dir
      ansible.builtin.file:
        path: "{{ install_dir }}/scripts/log"
        state: directory
      become: yes
      become_user: psm

    # run hourly at 21 minutes after the hour
    - name: Enable mongo cron script
      ansible.builtin.cron:
        name: mongo-full
        job: "cd {{ install_dir }}/scripts/; {{ install_dir }}/scripts/mongo-full.sh > /dev/null"
        minute: 21
        user: psm

    - name: Create recreate_status_changes.sh
      ansible.builtin.template:
        src: recreate_status_changes.sh.j2
        dest: "{{ install_dir }}/scripts/recreate_status_changes.sh"
        mode: '0755'
      become: yes
      become_user: psm

    # run hourly at 42 minutes after the hour
    - name: Enable recreate_status_changes cron
      ansible.builtin.cron:
        name: recreate_status_changes
        job: "cd {{ install_dir }}/scripts/; {{ install_dir }}/scripts/recreate_status_changes.sh > /dev/null"
        minute: 42
        user: psm

    # run the auto_requests script daily at 00:32
    - name: Add auto_requests to cron
      ansible.builtin.cron:
        name: auto_requests
        job: "cd {{ install_dir }}/scripts/; {{ install_dir }}/scripts/auto_requests.sh"
        hour: 0
        minute: 32
        user: psm

    - name: Reload Apache
      ansible.builtin.systemd:
        name: apache2
        state: reloaded
